# Use the official Python image from the DockerHub
FROM python:3.9-slim

# Set the working directory in docker
WORKDIR /app

# Copy the consolidated requirements.txt
COPY requirements.txt ./

RUN apt-get update && \
    apt-get install -y gcc libffi-dev libssl-dev curl

RUN pip3 install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local directories to the working directory
COPY . ./dreambot

# Ensure the entrypoint script is executable
RUN chmod +x /app/dreambot/entrypoint.sh

# Specify the command to run on container start
CMD ["/app/dreambot/entrypoint.sh"]