# Use the official Node.js image from DockerHub
FROM node:14

# Set the working directory
WORKDIR /app/dreamweb

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Start the application
CMD ["npm", "start"]