# Use the official Python image from the DockerHub
FROM python:3.9-slim

# Set the working directory in docker
WORKDIR /app

# Copy the consolidated requirements.txt
COPY requirements.txt ./

RUN apt-get update && \
    apt-get install -y gcc libffi-dev libssl-dev curl wget

RUN pip3 install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local directories to the working directory
COPY . ./api

# Ensure the entrypoint script is executable
RUN chmod +x /app/api/entrypoint.sh

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz


# Specify the command to run on container start
CMD ["/app/api/entrypoint.sh"]